apiVersion: v1
kind: Service
metadata:
  name: geth
  namespace: eth
spec:
  selector:
    app: geth
  type: LoadBalancer
  ports:
    - name: rpc
      port: 8545
    - name: ws
      port: 8546
    - name: p2p
      port: 30303