apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  source:
    targetRevision: 1.11.6
  helm:
    values: |
        bpf:
          masquerade: false
        externalIPs:
          enabled: true
        hostPort:
          enabled: true
        hostServices:
          enabled: false
        hubble:
          relay:
            enabled: true
          ui:
            enabled: true
        image:
          pullPolicy: IfNotPresent
        ipam:
          mode: kubernetes
        kubeProxyReplacement: partial
        nodePort:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
