apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  source:
    targetRevision: v1.11.6
    helm:
      values: |
          bpf:
            masquerade: false
          externalIPs:
            enabled: true
          hostPort:
            enabled: true
          hostServices:
            enabled: false
          hubble:
            relay:
              affinity:
                nodeAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 1
                      preference:
                        matchExpressions:
                          - key: node-role.kubernetes.io/master
                            operator: DoesNotExist
              enabled: true
              replicas: 1
            ui:
              enabled: true
              affinity:
                nodeAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 1
                      preference:
                        matchExpressions:
                          - key: node-role.kubernetes.io/master
                            operator: DoesNotExist
          image:
            pullPolicy: IfNotPresent
          ipam:
            mode: kubernetes
          kubeProxyReplacement: partial
          nodePort:
            enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
