apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/core
  - metallb-ranges.yaml
patches:
  - path: cert-manager.yaml
  - path: cilium.yaml
  - path: metrics-server.yaml
