apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-apps
  namespace: argocd
spec:
  project: ""
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: kustomization/overlays/dev/internal
    repoURL: https://github.com/OpsPita/argocd-gitops-example.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
